/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mibot3117
 */
public class frmSummativeQuiz extends javax.swing.JFrame {

    /**
     * Creates new form frmSummativeQuiz
     */
    public frmSummativeQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQuiz = new javax.swing.JPanel();
        lblQuizTitle = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();
        lblInstructions2 = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        lblOption1 = new javax.swing.JLabel();
        lblOption2 = new javax.swing.JLabel();
        lblOption3 = new javax.swing.JLabel();
        lblOption4 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        lblAnswerPrompt = new javax.swing.JLabel();
        lblFeedback = new javax.swing.JLabel();
        lblAmountCorrect = new javax.swing.JLabel();
        lblAmountIncorrect = new javax.swing.JLabel();
        lblPercentage = new javax.swing.JLabel();
        lblAmountCorrectResult = new javax.swing.JLabel();
        lblAmountIncorrectResult = new javax.swing.JLabel();
        lblPercentageResult = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlQuiz.setBackground(new java.awt.Color(255, 204, 204));
        pnlQuiz.setForeground(new java.awt.Color(255, 51, 51));

        lblQuizTitle.setFont(new java.awt.Font("Vineta BT", 0, 24)); // NOI18N
        lblQuizTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblQuizTitle.setText("The Quiz of Life");

        lblInstructions1.setFont(new java.awt.Font("Vineta BT", 0, 14)); // NOI18N
        lblInstructions1.setForeground(new java.awt.Color(0, 102, 102));
        lblInstructions1.setText("Write the correct letter in the text field and click");
        lblInstructions1.setToolTipText("");

        lblInstructions2.setFont(new java.awt.Font("Vineta BT", 0, 14)); // NOI18N
        lblInstructions2.setForeground(new java.awt.Color(0, 102, 102));
        lblInstructions2.setText("next to complete the quiz.");
        lblInstructions2.setToolTipText("");

        lblQuestion.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(0, 102, 102));
        lblQuestion.setText("What is the answer to life, the universe and everything?");
        lblQuestion.setToolTipText("");

        lblOption1.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblOption1.setForeground(new java.awt.Color(0, 102, 102));
        lblOption1.setText("A) Love");
        lblOption1.setToolTipText("");

        lblOption2.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblOption2.setForeground(new java.awt.Color(0, 102, 102));
        lblOption2.setText("B) 42");
        lblOption2.setToolTipText("");

        lblOption3.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblOption3.setForeground(new java.awt.Color(0, 102, 102));
        lblOption3.setText("C) We don't know");
        lblOption3.setToolTipText("");

        lblOption4.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblOption4.setForeground(new java.awt.Color(0, 102, 102));
        lblOption4.setText("D) 1764");
        lblOption4.setToolTipText("");

        lblAnswerPrompt.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblAnswerPrompt.setForeground(new java.awt.Color(0, 102, 102));
        lblAnswerPrompt.setText("Answer here:");
        lblAnswerPrompt.setToolTipText("");

        lblFeedback.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(0, 102, 102));
        lblFeedback.setText("Good Luck!");
        lblFeedback.setToolTipText("");

        lblAmountCorrect.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblAmountCorrect.setForeground(new java.awt.Color(0, 102, 102));
        lblAmountCorrect.setText("Amount Correct:");
        lblAmountCorrect.setToolTipText("");

        lblAmountIncorrect.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblAmountIncorrect.setForeground(new java.awt.Color(0, 102, 102));
        lblAmountIncorrect.setText("Amount Incorrect:");
        lblAmountIncorrect.setToolTipText("");

        lblPercentage.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N
        lblPercentage.setForeground(new java.awt.Color(0, 102, 102));
        lblPercentage.setText("Percentage:");
        lblPercentage.setToolTipText("");

        lblAmountCorrectResult.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N

        lblAmountIncorrectResult.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N

        lblPercentageResult.setFont(new java.awt.Font("Vineta BT", 0, 12)); // NOI18N

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuizLayout = new javax.swing.GroupLayout(pnlQuiz);
        pnlQuiz.setLayout(pnlQuizLayout);
        pnlQuizLayout.setHorizontalGroup(
            pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuizLayout.createSequentialGroup()
                .addGroup(pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuizLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lblQuizTitle))
                    .addGroup(pnlQuizLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblInstructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQuizLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lblInstructions2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQuizLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOption1)
                            .addComponent(lblQuestion)
                            .addComponent(lblOption2)
                            .addComponent(lblOption3)
                            .addComponent(lblOption4)
                            .addGroup(pnlQuizLayout.createSequentialGroup()
                                .addGroup(pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlQuizLayout.createSequentialGroup()
                                        .addComponent(lblAmountCorrect)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAmountCorrectResult, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlQuizLayout.createSequentialGroup()
                                        .addComponent(lblAnswerPrompt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuizLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAmountIncorrect)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAmountIncorrectResult, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(lblPercentage))
                                    .addGroup(pnlQuizLayout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(lblFeedback)
                                        .addGap(181, 181, 181)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPercentageResult, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlQuizLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnNext)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlQuizLayout.setVerticalGroup(
            pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuizTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructions1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstructions2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnswerPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAmountCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAmountIncorrect)
                        .addComponent(lblPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAmountCorrectResult, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAmountIncorrectResult, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPercentageResult, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSummativeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSummativeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSummativeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSummativeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSummativeQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lblAmountCorrect;
    private javax.swing.JLabel lblAmountCorrectResult;
    private javax.swing.JLabel lblAmountIncorrect;
    private javax.swing.JLabel lblAmountIncorrectResult;
    private javax.swing.JLabel lblAnswerPrompt;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JLabel lblOption1;
    private javax.swing.JLabel lblOption2;
    private javax.swing.JLabel lblOption3;
    private javax.swing.JLabel lblOption4;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JLabel lblPercentageResult;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblQuizTitle;
    private javax.swing.JPanel pnlQuiz;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
